# Generated by Django 4.2.30 on 2026-06-28 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_profile_account_name_profile_account_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=255)),
                ("actor_name", models.CharField(blank=True, max_length=255, null=True)),
                ("actor_id", models.IntegerField(blank=True, null=True)),
                (
                    "auditable_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "auditable_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("request_id", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
