# Generated by Django 4.2.30 on 2026-06-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
