# Generated by Django 4.2.30 on 2026-06-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_projectsubmission_course_project_brief_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
