# Generated by Django 4.2.30 on 2026-06-29 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0005_alter_course_slug_alter_lesson_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="assigned_tutor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_lessons",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
