# Generated by Django 4.2.30 on 2026-07-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_lesson_assigned_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='material_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
