# Generated by Django 4.2.30 on 2026-07-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_course_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='additional_materials',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lesson',
            name='additional_videos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
