# Generated by Django 4.2.30 on 2026-07-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='questions_data',
            field=models.JSONField(default=list),
        ),
    ]
